from enum import Enum

class UserRole(str, Enum):
    ADMIN = "ADMIN"
    DRIVER = "DRIVER"
    CUSTOMER = "CUSTOMER"
    FACILITY = "FACILITY"

class CustomerType(str, Enum):
    PHARMACY = "PHARMACY"
    DISTRIBUTOR = "DISTRIBUTOR"
    HOSPITAL = "HOSPITAL"
    CLINIC = "CLINIC"


class DriverStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class VehicleStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    ASSIGNED = "ASSIGNED"
    MAINTENANCE = "MAINTENANCE"
    INACTIVE = "INACTIVE"


class VehicleType(str, Enum):
    BIKE = "BIKE"
    THREE_WHEELER = "THREE_WHEELER"
    VAN = "VAN"
    TRUCK = "TRUCK"

class PickupStatus(str, Enum):
    REQUESTED = "REQUESTED"
    SCHEDULED = "SCHEDULED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COLLECTED = "COLLECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class PickupPriority(str, Enum):
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"

class RouteStatus(str, Enum):
    DRAFT = "DRAFT"
    OPTIMIZING = "OPTIMIZING"
    READY = "READY"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class RouteStopType(str, Enum):
    PICKUP = "PICKUP"
    WAREHOUSE = "WAREHOUSE" 

class RouteStopStatus(str, Enum):
    PENDING = "PENDING"
    ARRIVED = "ARRIVED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class WarehouseIntakeStatus(str, Enum):
    PENDING = "PENDING"
    RECEIVED = "RECEIVED"
    DISCREPANCY = "DISCREPANCY"
    REJECTED = "REJECTED"


class WasteBinColor(str, Enum):
    YELLOW = "YELLOW"
    RED = "RED"
    WHITE = "WHITE"
    BLUE = "BLUE"
    BROWN = "BROWN"

class WasteType(str, Enum):
    HUMAN_ANATOMICAL = "HUMAN_ANATOMICAL"
    ANIMAL_ANATOMICAL = "ANIMAL_ANATOMICAL"
    SOILED = "SOILED"
    EXPIRED_DISCARDED_MEDICINE = "EXPIRED_DISCARDED_MEDICINE"
    CHEMICAL = "CHEMICAL"
    CHEMICAL_LIQUID = "CHEMICAL_LIQUID"

    CONTAMINATED_RECYCLABLE = "CONTAMINATED_RECYCLABLE"

    SHARPS = "SHARPS"

    GLASSWARE = "GLASSWARE"
    METALLIC_IMPLANT = "METALLIC_IMPLANT"

    HAZARDOUS_OTHER = "HAZARDOUS_OTHER"

class DisposalShipmentStatus(str, Enum):
    CREATED = "CREATED"
    IN_TRANSIT = "IN_TRANSIT"
    RECEIVED = "RECEIVED"
    DISCREPANCY = "DISCREPANCY"
    CANCELLED = "CANCELLED"
    DISPOSED = "DISPOSED"

class NotificationChannel(str, Enum):
    IN_APP = "IN_APP"
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"


class NotificationStatus(str, Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


class NotificationType(str, Enum):
    PICKUP_REQUESTED = "PICKUP_REQUESTED"
    PICKUP_SCHEDULED = "PICKUP_SCHEDULED"
    DRIVER_ASSIGNED = "DRIVER_ASSIGNED"
    PICKUP_COMPLETED = "PICKUP_COMPLETED"
    SHIPMENT_DISPATCHED = "SHIPMENT_DISPATCHED"
    SHIPMENT_RECEIVED = "SHIPMENT_RECEIVED"
    DISPOSAL_COMPLETED = "DISPOSAL_COMPLETED"