"""create disposal certificates and disposed status

Revision ID: 23f7980e9035
Revises: c7aa8663f38b
Create Date: 2026-09-30 15:58:05.065421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f7980e9035'
down_revision: Union[str, Sequence[str], None] = 'c7aa8663f38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disposal_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_code', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=150), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['disposal_shipments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disposal_certificates_certificate_code'), 'disposal_certificates', ['certificate_code'], unique=True)
    op.create_index(op.f('ix_disposal_certificates_shipment_id'), 'disposal_certificates', ['shipment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disposal_certificates_shipment_id'), table_name='disposal_certificates')
    op.drop_index(op.f('ix_disposal_certificates_certificate_code'), table_name='disposal_certificates')
    op.drop_table('disposal_certificates')
    op.execute(
        "ALTER TYPE disposalshipmentstatus ADD VALUE IF NOT EXISTS 'DISPOSED'"
    )
    # ### end Alembic commands ###
