"""add warehouse intake classification

Revision ID: 2f6e0f8269ee
Revises: 9b72c33eff3c
Create Date: 2026-09-30 15:23:32.654943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6e0f8269ee'
down_revision: Union[str, Sequence[str], None] = '9b72c33eff3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_intake_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('bin_color', sa.Enum('YELLOW', 'RED', 'WHITE', 'BLUE', 'BROWN', name='wastebincolor'), nullable=False),
    sa.Column('waste_type', sa.Enum('HUMAN_ANATOMICAL', 'ANIMAL_ANATOMICAL', 'SOILED', 'EXPIRED_DISCARDED_MEDICINE', 'CHEMICAL', 'CHEMICAL_LIQUID', 'CONTAMINATED_RECYCLABLE', 'SHARPS', 'GLASSWARE', 'METALLIC_IMPLANT', 'HAZARDOUS_OTHER', name='wastetype'), nullable=False),
    sa.Column('expected_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('received_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['warehouse_intakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intake_id', 'bin_color', 'waste_type', name='uq_intake_waste_type')
    )
    op.create_index(op.f('ix_warehouse_intake_items_intake_id'), 'warehouse_intake_items', ['intake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_intake_items_intake_id'), table_name='warehouse_intake_items')
    op.drop_table('warehouse_intake_items')
    # ### end Alembic commands ###
