"""add customer type profiles

Revision ID: 3028556e632f
Revises: b5994bf173a4
Create Date: 2026-09-24 22:23:53.987376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3028556e632f'
down_revision: Union[str, Sequence[str], None] = 'b5994bf173a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_type', sa.Enum('PHARMACY', 'DISTRIBUTOR', 'HOSPITAL', 'CLINIC', name='customer_type'), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('aadhar_number', sa.String(length=12), nullable=False),
    sa.Column('aadhar_photo', sa.String(length=500), nullable=True),
    sa.Column('dl_number', sa.String(length=50), nullable=True),
    sa.Column('dl_photo', sa.String(length=500), nullable=True),
    sa.Column('shop_photo', sa.String(length=500), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_aadhar_number'), 'customers', ['aadhar_number'], unique=True)
    op.create_index(op.f('ix_customers_dl_number'), 'customers', ['dl_number'], unique=True)
    op.create_index(op.f('ix_customers_gst_number'), 'customers', ['gst_number'], unique=True)
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=True)
    op.create_table('clinic_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('clinic_type', sa.String(length=100), nullable=True),
    sa.Column('doctor_name', sa.String(length=150), nullable=True),
    sa.Column('speciality', sa.String(length=150), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('registration_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_profiles_customer_id'), 'clinic_profiles', ['customer_id'], unique=True)
    op.create_table('customer_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address_line_1', sa.String(length=250), nullable=False),
    sa.Column('address_line_2', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('service_time_seconds', sa.Integer(), nullable=False),
    sa.Column('pickup_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_locations_customer_id'), 'customer_locations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_locations_location_code'), 'customer_locations', ['location_code'], unique=False)
    op.create_table('distributor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('distribution_license_number', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('aadhar_photo', sa.String(length=500), nullable=True),
    sa.Column('dl_number', sa.String(length=50), nullable=True),
    sa.Column('dl_photo', sa.String(length=500), nullable=True),
    sa.Column('shop_photo', sa.String(length=500), nullable=True),
    sa.Column('warehouse_count', sa.Integer(), nullable=False),
    sa.Column('coverage_area', sa.String(length=250), nullable=True),
    sa.Column('license_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributor_profiles_customer_id'), 'distributor_profiles', ['customer_id'], unique=True)
    op.create_index(op.f('ix_distributor_profiles_dl_number'), 'distributor_profiles', ['dl_number'], unique=True)
    op.create_table('hospital_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('hospital_type', sa.String(length=100), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('department_count', sa.Integer(), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('registration_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_profiles_customer_id'), 'hospital_profiles', ['customer_id'], unique=True)
    op.create_table('pharmacy_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_license_number', sa.String(length=100), nullable=True),
    sa.Column('pharmacist_name', sa.String(length=150), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('aadhar_photo', sa.String(length=500), nullable=True),
    sa.Column('dl_number', sa.String(length=50), nullable=True),
    sa.Column('dl_photo', sa.String(length=500), nullable=True),
    sa.Column('shop_photo', sa.String(length=500), nullable=True),
    sa.Column('license_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_profiles_customer_id'), 'pharmacy_profiles', ['customer_id'], unique=True)
    op.create_index(op.f('ix_pharmacy_profiles_dl_number'), 'pharmacy_profiles', ['dl_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_profiles_dl_number'), table_name='pharmacy_profiles')
    op.drop_index(op.f('ix_pharmacy_profiles_customer_id'), table_name='pharmacy_profiles')
    op.drop_table('pharmacy_profiles')
    op.drop_index(op.f('ix_hospital_profiles_customer_id'), table_name='hospital_profiles')
    op.drop_table('hospital_profiles')
    op.drop_index(op.f('ix_distributor_profiles_dl_number'), table_name='distributor_profiles')
    op.drop_index(op.f('ix_distributor_profiles_customer_id'), table_name='distributor_profiles')
    op.drop_table('distributor_profiles')
    op.drop_index(op.f('ix_customer_locations_location_code'), table_name='customer_locations')
    op.drop_index(op.f('ix_customer_locations_customer_id'), table_name='customer_locations')
    op.drop_table('customer_locations')
    op.drop_index(op.f('ix_clinic_profiles_customer_id'), table_name='clinic_profiles')
    op.drop_table('clinic_profiles')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_gst_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_dl_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_aadhar_number'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
