"""add whatsapp provider delivery status

Revision ID: 62019bdb37e0
Revises: 806beec671f5
Create Date: 2026-09-30 21:43:18.164971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62019bdb37e0'
down_revision: Union[str, Sequence[str], None] = '806beec671f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('provider_status', sa.String(length=30), nullable=True))
    op.add_column('notifications', sa.Column('provider_status_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'provider_status_at')
    op.drop_column('notifications', 'provider_status')
    # ### end Alembic commands ###
