"""normalize customer schema

Revision ID: 7b6dc0755085
Revises: 3028556e632f
Create Date: 2026-09-27 15:27:17.464454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b6dc0755085'
down_revision: Union[str, Sequence[str], None] = '3028556e632f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('AADHAAR', 'DRUG_LICENSE', 'BUSINESS_REGISTRATION', 'GST_CERTIFICATE', 'OTHER', name='customer_document_type'), nullable=False),
    sa.Column('document_number', sa.String(length=150), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_documents_customer_id'), 'customer_documents', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_clinic_profiles_customer_id'), table_name='clinic_profiles')
    op.create_index(op.f('ix_clinic_profiles_customer_id'), 'clinic_profiles', ['customer_id'], unique=False)
    op.create_unique_constraint('uq_clinic_profiles_customer_id', 'clinic_profiles', ['customer_id'])
    op.drop_column('clinic_profiles', 'gstin')
    op.add_column('customer_locations', sa.Column('location_photo', sa.String(length=500), nullable=True))
    op.alter_column('customer_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('customer_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_customer_locations_location_code'), table_name='customer_locations')
    op.create_unique_constraint('uq_customer_location_code', 'customer_locations', ['customer_id', 'location_code'])
    op.alter_column('customers', 'gst_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_customers_aadhar_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_dl_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_gst_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=False)
    op.create_unique_constraint('uq_customers_user_id', 'customers', ['user_id'])
    op.drop_column('customers', 'dl_number')
    op.drop_column('customers', 'aadhar_number')
    op.drop_column('customers', 'shop_photo')
    op.drop_column('customers', 'aadhar_photo')
    op.drop_column('customers', 'dl_photo')
    op.drop_index(op.f('ix_distributor_profiles_dl_number'), table_name='distributor_profiles')
    op.drop_index(op.f('ix_distributor_profiles_customer_id'), table_name='distributor_profiles')
    op.create_index(op.f('ix_distributor_profiles_customer_id'), 'distributor_profiles', ['customer_id'], unique=False)
    op.create_unique_constraint('uq_distributor_profiles_customer_id', 'distributor_profiles', ['customer_id'])
    op.drop_column('distributor_profiles', 'dl_number')
    op.drop_column('distributor_profiles', 'gstin')
    op.drop_column('distributor_profiles', 'shop_photo')
    op.drop_column('distributor_profiles', 'aadhar_photo')
    op.drop_column('distributor_profiles', 'dl_photo')
    op.drop_index(op.f('ix_hospital_profiles_customer_id'), table_name='hospital_profiles')
    op.create_index(op.f('ix_hospital_profiles_customer_id'), 'hospital_profiles', ['customer_id'], unique=False)
    op.create_unique_constraint('uq_hospital_profiles_customer_id', 'hospital_profiles', ['customer_id'])
    op.drop_column('hospital_profiles', 'bed_count')
    op.drop_column('hospital_profiles', 'gstin')
    op.drop_index(op.f('ix_pharmacy_profiles_dl_number'), table_name='pharmacy_profiles')
    op.drop_index(op.f('ix_pharmacy_profiles_customer_id'), table_name='pharmacy_profiles')
    op.create_index(op.f('ix_pharmacy_profiles_customer_id'), 'pharmacy_profiles', ['customer_id'], unique=False)
    op.create_unique_constraint('uq_pharmacy_profiles_customer_id', 'pharmacy_profiles', ['customer_id'])
    op.drop_column('pharmacy_profiles', 'dl_number')
    op.drop_column('pharmacy_profiles', 'gstin')
    op.drop_column('pharmacy_profiles', 'shop_photo')
    op.drop_column('pharmacy_profiles', 'aadhar_photo')
    op.drop_column('pharmacy_profiles', 'dl_photo')
    op.alter_column(
        "users",
        "auth_user_id",
        existing_type=sa.VARCHAR(length=100),
        type_=postgresql.UUID(as_uuid=True),
        existing_nullable=False,
        postgresql_using="auth_user_id::uuid",
    )
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'auth_user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('pharmacy_profiles', sa.Column('dl_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('pharmacy_profiles', sa.Column('aadhar_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('pharmacy_profiles', sa.Column('shop_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('pharmacy_profiles', sa.Column('gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('pharmacy_profiles', sa.Column('dl_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint('uq_pharmacy_profiles_customer_id', 'pharmacy_profiles', type_='unique')
    op.drop_index(op.f('ix_pharmacy_profiles_customer_id'), table_name='pharmacy_profiles')
    op.create_index(op.f('ix_pharmacy_profiles_customer_id'), 'pharmacy_profiles', ['customer_id'], unique=True)
    op.create_index(op.f('ix_pharmacy_profiles_dl_number'), 'pharmacy_profiles', ['dl_number'], unique=True)
    op.add_column('hospital_profiles', sa.Column('gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('hospital_profiles', sa.Column('bed_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_hospital_profiles_customer_id', 'hospital_profiles', type_='unique')
    op.drop_index(op.f('ix_hospital_profiles_customer_id'), table_name='hospital_profiles')
    op.create_index(op.f('ix_hospital_profiles_customer_id'), 'hospital_profiles', ['customer_id'], unique=True)
    op.add_column('distributor_profiles', sa.Column('dl_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('distributor_profiles', sa.Column('aadhar_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('distributor_profiles', sa.Column('shop_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('distributor_profiles', sa.Column('gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('distributor_profiles', sa.Column('dl_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint('uq_distributor_profiles_customer_id', 'distributor_profiles', type_='unique')
    op.drop_index(op.f('ix_distributor_profiles_customer_id'), table_name='distributor_profiles')
    op.create_index(op.f('ix_distributor_profiles_customer_id'), 'distributor_profiles', ['customer_id'], unique=True)
    op.create_index(op.f('ix_distributor_profiles_dl_number'), 'distributor_profiles', ['dl_number'], unique=True)
    op.add_column('customers', sa.Column('dl_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('aadhar_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('shop_photo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('aadhar_number', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('dl_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint('uq_customers_user_id', 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=True)
    op.create_index(op.f('ix_customers_gst_number'), 'customers', ['gst_number'], unique=True)
    op.create_index(op.f('ix_customers_dl_number'), 'customers', ['dl_number'], unique=True)
    op.create_index(op.f('ix_customers_aadhar_number'), 'customers', ['aadhar_number'], unique=True)
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customers', 'gst_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_constraint('uq_customer_location_code', 'customer_locations', type_='unique')
    op.create_index(op.f('ix_customer_locations_location_code'), 'customer_locations', ['location_code'], unique=False)
    op.alter_column('customer_locations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customer_locations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('customer_locations', 'location_photo')
    op.add_column('clinic_profiles', sa.Column('gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint('uq_clinic_profiles_customer_id', 'clinic_profiles', type_='unique')
    op.drop_index(op.f('ix_clinic_profiles_customer_id'), table_name='clinic_profiles')
    op.create_index(op.f('ix_clinic_profiles_customer_id'), 'clinic_profiles', ['customer_id'], unique=True)
    op.drop_index(op.f('ix_customer_documents_customer_id'), table_name='customer_documents')
    op.drop_table('customer_documents')
    # ### end Alembic commands ###
