"""create pickups

Revision ID: 7d76d05caba7
Revises: 9fbc2f98ac76
Create Date: 2026-09-27 19:06:20.091294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d76d05caba7'
down_revision: Union[str, Sequence[str], None] = '9fbc2f98ac76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_code', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'SCHEDULED', 'ASSIGNED', 'IN_PROGRESS', 'COLLECTED', 'FAILED', 'CANCELLED', name='pickupstatus'), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'URGENT', name='pickuppriority'), nullable=False),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['customer_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pickup_code')
    )
    op.create_index(op.f('ix_pickups_customer_id'), 'pickups', ['customer_id'], unique=False)
    op.create_index(op.f('ix_pickups_id'), 'pickups', ['id'], unique=False)
    op.create_index(op.f('ix_pickups_location_id'), 'pickups', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickups_location_id'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_id'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_customer_id'), table_name='pickups')
    op.drop_table('pickups')
    # ### end Alembic commands ###
