"""add configuration audit trail

Revision ID: 90a1a2bb2360
Revises: c841fadba61c
Create Date: 2026-09-30 22:14:33.387768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a1a2bb2360'
down_revision: Union[str, Sequence[str], None] = 'c841fadba61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('configuration_version_id', sa.Integer(), nullable=True),
    sa.Column('change_request_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('change_reference', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['change_request_id'], ['configuration_changes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['configuration_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_audits_action'), 'configuration_audits', ['action'], unique=False)
    op.create_index(op.f('ix_configuration_audits_actor_id'), 'configuration_audits', ['actor_id'], unique=False)
    op.create_index(op.f('ix_configuration_audits_change_request_id'), 'configuration_audits', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_configuration_audits_configuration_id'), 'configuration_audits', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_configuration_audits_configuration_version_id'), 'configuration_audits', ['configuration_version_id'], unique=False)
    op.create_index(op.f('ix_configuration_audits_created_at'), 'configuration_audits', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuration_audits_created_at'), table_name='configuration_audits')
    op.drop_index(op.f('ix_configuration_audits_configuration_version_id'), table_name='configuration_audits')
    op.drop_index(op.f('ix_configuration_audits_configuration_id'), table_name='configuration_audits')
    op.drop_index(op.f('ix_configuration_audits_change_request_id'), table_name='configuration_audits')
    op.drop_index(op.f('ix_configuration_audits_actor_id'), table_name='configuration_audits')
    op.drop_index(op.f('ix_configuration_audits_action'), table_name='configuration_audits')
    op.drop_table('configuration_audits')
    # ### end Alembic commands ###
