"""create warehouse intake

Revision ID: 9b72c33eff3c
Revises: e65ab9b268b4
Create Date: 2026-09-30 15:02:03.503876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b72c33eff3c'
down_revision: Union[str, Sequence[str], None] = 'e65ab9b268b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_code', sa.String(length=50), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'DISCREPANCY', 'REJECTED', name='warehouseintakestatus'), nullable=False),
    sa.Column('expected_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('received_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discrepancy_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intake_code')
    )
    op.create_index(op.f('ix_warehouse_intakes_driver_id'), 'warehouse_intakes', ['driver_id'], unique=False)
    op.create_index(op.f('ix_warehouse_intakes_route_id'), 'warehouse_intakes', ['route_id'], unique=True)
    op.create_index(op.f('ix_warehouse_intakes_vehicle_id'), 'warehouse_intakes', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_warehouse_intakes_warehouse_id'), 'warehouse_intakes', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_intakes_warehouse_id'), table_name='warehouse_intakes')
    op.drop_index(op.f('ix_warehouse_intakes_vehicle_id'), table_name='warehouse_intakes')
    op.drop_index(op.f('ix_warehouse_intakes_route_id'), table_name='warehouse_intakes')
    op.drop_index(op.f('ix_warehouse_intakes_driver_id'), table_name='warehouse_intakes')
    op.drop_table('warehouse_intakes')
    # ### end Alembic commands ###
