"""add driver vehicle assignments

Revision ID: 9fbc2f98ac76
Revises: a648c5da895f
Create Date: 2026-09-27 17:20:33.336363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbc2f98ac76'
down_revision: Union[str, Sequence[str], None] = 'a648c5da895f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_vehicle_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('unassigned_at IS NULL OR unassigned_at > assigned_at', name='ck_assignment_valid_dates'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_vehicle_assignments_driver_id'), 'driver_vehicle_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_vehicle_assignments_vehicle_id'), 'driver_vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_index('uq_active_driver_assignment', 'driver_vehicle_assignments', ['driver_id'], unique=True, postgresql_where=sa.text('unassigned_at IS NULL'))
    op.create_index('uq_active_vehicle_assignment', 'driver_vehicle_assignments', ['vehicle_id'], unique=True, postgresql_where=sa.text('unassigned_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_vehicle_assignment', table_name='driver_vehicle_assignments', postgresql_where=sa.text('unassigned_at IS NULL'))
    op.drop_index('uq_active_driver_assignment', table_name='driver_vehicle_assignments', postgresql_where=sa.text('unassigned_at IS NULL'))
    op.drop_index(op.f('ix_driver_vehicle_assignments_vehicle_id'), table_name='driver_vehicle_assignments')
    op.drop_index(op.f('ix_driver_vehicle_assignments_driver_id'), table_name='driver_vehicle_assignments')
    op.drop_table('driver_vehicle_assignments')
    # ### end Alembic commands ###
