"""add rollback reference to configuration changes

Revision ID: b856cc4dd242
Revises: 90a1a2bb2360
Create Date: 2026-09-30 22:32:57.976837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b856cc4dd242'
down_revision: Union[str, Sequence[str], None] = '90a1a2bb2360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration_changes', sa.Column('rollback_of_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'configuration_changes', 'configuration_versions', ['rollback_of_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'configuration_changes', type_='foreignkey')
    op.drop_column('configuration_changes', 'rollback_of_version_id')
    # ### end Alembic commands ###
