"""create disposal shipments

Revision ID: c7aa8663f38b
Revises: f3bca86fd5e2
Create Date: 2026-09-30 15:46:58.038596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7aa8663f38b'
down_revision: Union[str, Sequence[str], None] = 'f3bca86fd5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disposal_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_code', sa.String(length=50), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_TRANSIT', 'RECEIVED', 'DISCREPANCY', 'CANCELLED', name='disposalshipmentstatus'), nullable=False),
    sa.Column('expected_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('received_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discrepancy_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expected_weight_kg > 0', name='ck_disposal_shipments_expected_weight_positive'),
    sa.CheckConstraint('received_weight_kg IS NULL OR received_weight_kg >= 0', name='ck_disposal_shipments_received_weight_nonnegative'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['intake_id'], ['warehouse_intakes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disposal_shipments_facility_id'), 'disposal_shipments', ['facility_id'], unique=False)
    op.create_index(op.f('ix_disposal_shipments_intake_id'), 'disposal_shipments', ['intake_id'], unique=False)
    op.create_index(op.f('ix_disposal_shipments_shipment_code'), 'disposal_shipments', ['shipment_code'], unique=True)
    op.create_table('disposal_shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_intake_item_id', sa.Integer(), nullable=False),
    sa.Column('expected_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('received_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('expected_weight_kg > 0', name='ck_disposal_shipment_items_expected_weight_positive'),
    sa.CheckConstraint('received_weight_kg IS NULL OR received_weight_kg >= 0', name='ck_disposal_shipment_items_received_weight_nonnegative'),
    sa.ForeignKeyConstraint(['shipment_id'], ['disposal_shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_intake_item_id'], ['warehouse_intake_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'warehouse_intake_item_id', name='uq_disposal_shipment_item')
    )
    op.create_index(op.f('ix_disposal_shipment_items_shipment_id'), 'disposal_shipment_items', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_disposal_shipment_items_warehouse_intake_item_id'), 'disposal_shipment_items', ['warehouse_intake_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disposal_shipment_items_warehouse_intake_item_id'), table_name='disposal_shipment_items')
    op.drop_index(op.f('ix_disposal_shipment_items_shipment_id'), table_name='disposal_shipment_items')
    op.drop_table('disposal_shipment_items')
    op.drop_index(op.f('ix_disposal_shipments_shipment_code'), table_name='disposal_shipments')
    op.drop_index(op.f('ix_disposal_shipments_intake_id'), table_name='disposal_shipments')
    op.drop_index(op.f('ix_disposal_shipments_facility_id'), table_name='disposal_shipments')
    op.drop_table('disposal_shipments')
    # ### end Alembic commands ###
