"""add estimated pickup weight

Revision ID: d8c1355407a3
Revises: b95098ffdf10
Create Date: 2026-09-27 22:26:01.861929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c1355407a3'
down_revision: Union[str, Sequence[str], None] = 'b95098ffdf10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickups', sa.Column('estimated_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_constraint(op.f('uq_route_stops_route_sequence'), 'route_stops', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_route_stops_route_sequence'), 'route_stops', ['route_id', 'sequence_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('pickups', 'estimated_weight_kg')
    # ### end Alembic commands ###
