"""add collection proof to route stops

Revision ID: e65ab9b268b4
Revises: 9d4d61acc879
Create Date: 2026-09-30 14:23:08.316978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65ab9b268b4'
down_revision: Union[str, Sequence[str], None] = '9d4d61acc879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_stops', sa.Column('proof_storage_path', sa.String(length=500), nullable=True))
    op.add_column('route_stops', sa.Column('proof_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_stops', 'proof_uploaded_at')
    op.drop_column('route_stops', 'proof_storage_path')
    # ### end Alembic commands ###
